[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Advent of Code, 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=12.3,<13",
    "ansible-lint==25.12.1",
]
